name: pet_finder
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - flask
  - pymongo
  - pandas
  - numpy
  - pillow
  - timm
  - pytorch
  - torchvision
  - torchaudio
  - flask-cors
  - pip:
      - torchtext
      - pytorch-lightning
      - jupyterlab
