name: envpt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.* 
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - pillow
  - pyyaml
  - zstd
  - zstandard
  - yaml
  - tornado
  - sympy
  - cffi
  - openssl
  - lcms2
  - lerc
  - tk
  - fonttools
  - xorg-libxau # Optional: Only if needed for specific dependencies
  - xorg-libxdmcp # Optional: Only if needed for specific dependencies
  - pip
