name: envpt
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pyyaml
  - zstd
  - zstandard
  - yaml
  - tornado
  - sympy
  - cffi
  - openssl
  - flask
  - lcms2
  - lerc
  - tk
  - fonttools
  - xorg-libxau # Optional: Only if needed for specific dependencies
  - xorg-libxdmcp # Optional: Only if needed for specific dependencies
  - pip
  - pytorch
  - torchvision
  - matplotlib
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - flask
  - flask-cors
  - flask-restful
  - tk
  - pyyaml
  - pillow
  - pymongo

